In [2]:
import pickle

with open('./custom_mosi.pickle', 'rb') as fp:
    data = pickle.load(fp)

In [29]:
print(data.keys())
print(data['train'].keys())
print(data['train']['vision'][0].shape)
print(data['train']['audio'][0].shape)
print(data['train']['text'][0].shape)
print(data['train']['labels'][25])
print(data['train']['mask'][0].shape)

dict_keys(['train', 'test', 'valid'])
dict_keys(['vision', 'audio', 'text', 'labels', 'mask'])
(35,)
(1585,)
(300,)
[[-0.8]]
(50,)


In [30]:
print(data['train']['labels'])

[array([2.4], dtype=float32), array([2.4], dtype=float32), array([2.4], dtype=float32), array([2.4], dtype=float32), array([2.4], dtype=float32), array([[2.4]], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([-0.8], dtype=float32), array([[-0.8]], dtype=float32), array([-1.], dtype=float32), array([-1.], dtype=float32), array([-1.], dtype=float32), array([-1.], dtype=float32), array([-1.], dtype=float32), array([-1.], dtype=float32), array([-1.], dtype=float32), array([-1.], dtype

In [4]:
data['train'].keys()

dict_keys(['vision', 'audio', 'text', 'labels', 'mask'])

In [6]:
some_id = 0
print(f"Keys -> {data.keys()}")
print(f"Keys belonging to `train` set -> {data['train'].keys()}")
print(f"Shape of Vision Feature of ID {some_id} -> {data['train']['vision'][some_id].shape}")
print(f"Shape of Audio Feature of ID {some_id} -> {data['train']['audio'][some_id].shape}")
print(f"Shape of Text Feature of ID {some_id} -> {data['train']['text'][some_id].shape}")
print(f"Labels of ID {some_id} -> {data['train']['labels'][some_id]}")
print(f"Mask of ID {some_id} -> {data['train']['mask'][some_id]}")

Keys -> dict_keys(['train', 'test', 'valid'])
Keys belonging to `train` set -> dict_keys(['vision', 'audio', 'text', 'labels', 'mask'])
Shape of Vision Feature of ID 0 -> (35,)
Shape of Audio Feature of ID 0 -> (1585,)
Shape of Text Feature of ID 0 -> (300,)
Labels of ID 0 -> [2.4]
Mask of ID 0 -> [1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [21]:
for i in range(16265):
    print(data['train']['vision'][i][-1])
    cur = data['train']['labels'][i]
    if len(cur) > 1:
        print(data['train']['vision'][i].shape)
        print(data['train']['audio'][i].shape)
        print(data['train']['text'][i].shape)
        print(data['train']['labels'][i])
        print(data['train']['id'][i])

-0.1864848
1.7606788
0.21770234
-1.2218257
-0.57007164
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1.270813
2.1118073
-0.65805936
-0.3809872
0.37841716
-0.120153256
-1.7540839
-1.7031816
-0.9548349
1.5891808
1.4621366
-0.22450724
0.056840934
-0.21322475
-0.64819324
-0.33084145
0.0389843
-0.0010829177
0.08096942
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
0.18474147
0.4810687
0.88842416
0.9571613
0.75150174
0.7690518
-0.8054026
-1.5162748
-1.7102715
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-1.9904071
0.50084263
0.4178774
0.67469394
0.39699313
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1.7215811
-0.39709136
-0.6363633
-0.6881271
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [51]:
data['train']['labels']

[array([2.4], dtype=float32),
 array([2.4], dtype=float32),
 array([2.4], dtype=float32),
 array([2.4], dtype=float32),
 array([2.4], dtype=float32),
 array([[2.4]], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([-0.8], dtype=float32),
 array([[-0.8]], dtype=float32),
 array([-1.], dtype=float32),
 array([-1.], dtype=float32),
 array([-1.], dtype=float32),
 array([-1.], dtype=float32),
 array([-1.], dtype=float32),
 array([-1.], dtype=float32),
 array([-1.], dt

In [63]:
import numpy as np

def cmumosei_round(a):
    if a < -2:
        res = -3
    if -2 <= a and a < -1:
        res = -2
    if -1 <= a and a < 0:
        res = -1
    if 0 <= a and a <= 0:
            res = 0
    if 0 < a and a <= 1:
            res = 1
    if 1 < a and a <= 2:
            res = 2
    if a > 2:
            res = 3
    return res

labels = []
for i in data['train']['labels']:
      if type(i[0]).__name__ == 'ndarray':
        labels.append(i[0][0])
        continue
      else:
        labels.append(i[0])

labelset = sorted(list(set([cmumosei_round(label) for label in labels])))
print(labelset)

[-3, -2, -1, 0, 1, 2, 3]
